In [ ]:
import numpy as np

In [ ]:
# 61.Find the nearest value in an array
Z = np.array([1, 4, 8, 12, 15])
value = 8

index = (np.abs(Z - value)).argmin()
nearest_value = Z[index]

print("Nearest value: ", nearest_value)

Nearest value:  8


In [ ]:
#62.  Sum arrays of shape (1,3) and (3,1) using an iterator

A = np.arange(3).reshape((1, 3))
B = np.arange(3).reshape((3, 1))

iterator = np.nditer([A, B, None],
    flags=["external_loop"],
    op_flags=[
       ["readonly"],
       ["readonly"],
       ["writeonly", "allocate"]
    ]
)

for x, y, result in iterator:
    result[...] = x + y

print(iterator.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
#63.  Create a class with a name attribute
class NamedArray(np.ndarray):

    def __new__(cls, values, name="No name"):
        obj = np.asarray(values).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return

        self.name = getattr(obj, "name", "No name")


Z = NamedArray([1, 2, 3, 4], name="My Array")

print(Z)
print(Z.name)

[1 2 3 4]
My Array


In [ ]:
#64. Add 1 to elements indexed by another vector
Z = np.zeros(10, dtype=int)
indices = np.array([1, 2, 3, 2, 4, 3, 3])

np.add.at(Z, indices, 1)

print(Z)

[0 1 2 3 1 0 0 0 0 0]


In [ ]:
# 65. Accumulate vector values into another array
X = np.array([1, 2, 3, 4, 5, 6])
I = np.array([0, 1, 1, 2, 2, 2])

F = np.zeros(3, dtype=int)
np.add.at(F, I, X)

print(F)

[ 1  5 15]


In [ ]:
#66. Count unique colors in an image
width = 5
height = 4

image = np.random.randint(
    0,
    256,
    size=(width, height, 3),
    dtype=np.uint8
)

colours = image.reshape(-1, 3)
unique_colours = np.unique(colours, axis=0)

print("Number of unique colours:", len(unique_colours))

Number of unique colours: 20


In [ ]:
# 67. Sum over the last two axes of a 3D array

Z = np.random.randint(1, 10, (2, 3, 4, 5))

result = Z.sum(axis=(-2, -1))
print("Original shape:", Z.shape)
print("Result shape:", result.shape)
print(result)


Original shape: (2, 3, 4, 5)
Result shape: (2, 3)
[[104 106 102]
 [ 99 104 104]]


In [ ]:
# 68. Calculate means of subsets

D = np.array ([10, 20, 30, 40, 50, 60])
S = np.array ([0, 0, 1, 1, 2, 2])

subset_sums = np.bincount(S, weights=D)
subset_counts = np.bincount(S)
subset_means = subset_sums / np.bincount(S)

print(subset_means)

[15. 35. 55.]


In [ ]:
#69. Get the diagonal of a dot product

A = np.random.randint(1, 10, size=(3, 4))
B = np.random.randint(1, 10, size=(4, 3))

diagonal = np.diag(np.dot(A, B))
print("Diagonal of the dot product:", diagonal)

Diagonal of the dot product: [ 44 112  73]


In [ ]:
# 70. Insert three zeros between each value 

Z = np.array ([1, 2, 3, 4, 5])

number_of_zeros = 3

result = np.zeros(
    len(Z) + (len(Z) - 1) * number_of_zeros,
    dtype=Z.dtype

)
result[::number_of_zeros + 1] = Z

print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


In [ ]:
# 71. Multiply arrays of shapes(5,5,3) and(5,5)
A = np.random.randint(1, 10, size=(5, 5, 3))
B = np.random.randint(1, 10, size=(5, 5))

result = A * B[:, :, np.newaxis]
print(result.shape)


(5, 5, 3)


In [ ]:
# 72. Swap two rows
Z = np.arange(25).reshape(5, 5)

print("Before swapping:")
print(Z)

# Swap rows 0 and 4
Z[[0, 4]] = Z[[4, 0]]

print("After swapping:")
print(Z)

Before swapping:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
After swapping:
[[20 21 22 23 24]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


In [ ]:
# 73. Find uniques line segments from triangles

triangles = np.random.randint(0, 100, size=(10, 3, 2))

edges = triangles[:, [[0, 1], [1, 2], [2, 0]]]

edges = edges.reshape(-1, 2)

# Sort the edges to ensure that each edge is represented in a consistent order
edges = np.sort(edges, axis=1)

unique_edges = np.unique(edges, axis=0)

print("Unique edges:")
print(unique_edges)

print("Triangles:")
print(triangles)

Unique edges:
[[ 1 24]
 [ 1 69]
 [ 3 68]
 [ 4 60]
 [ 4 75]
 [ 7 38]
 [11 13]
 [13 30]
 [13 67]
 [14 74]
 [14 80]
 [17 96]
 [18 67]
 [23 39]
 [23 42]
 [23 64]
 [25 51]
 [28 79]
 [31 71]
 [33 45]
 [36 79]
 [42 78]
 [54 59]
 [55 68]
 [56 97]
 [62 75]
 [67 72]
 [69 83]
 [76 93]
 [77 95]]
Triangles:
[[[67 72]
  [38  7]
  [51 25]]

 [[67 13]
  [68  3]
  [76 93]]

 [[14 74]
  [24  1]
  [55 68]]

 [[69 83]
  [77 95]
  [69  1]]

 [[23 64]
  [59 54]
  [18 67]]

 [[13 11]
  [30 13]
  [79 36]]

 [[78 42]
  [39 23]
  [14 80]]

 [[79 28]
  [96 17]
  [56 97]]

 [[23 42]
  [ 4 75]
  [71 31]]

 [[33 45]
  [ 4 60]
  [75 62]]]


In [ ]:
# 74. Produce an array whose bicount equals C

C = np.array([2, 3, 1, 4 ])
A = np.repeat(np.arange(len(C)), C)

print("A:", A)
print("Bincount: ", np.bincount(A))

A: [0 0 1 1 1 2 3 3 3 3]
Bincount:  [2 3 1 4]


In [ ]:
# 75. Sliding window averages
Z = np.array([1, 2, 3, 4, 5, 6])
window_size = 3

averages = np.convolve(
    Z,
    np.ones(window_size) / window_size,
    mode="valid"
)
print(averages)

[2. 3. 4. 5.]


In [ ]:
# 76. Create a shifted 2D array
Z= np.arange(1, 11)
result = np.lib.stride_tricks.sliding_window_view(Z, window_shape=3)
print(result)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


In [ ]:
# Negative booleans and floats in place 
Boolean Values 
Z = np.array([True, False, True, False])

Z[Z == True] = False
Z[Z == False] = True

print(Z)


[ True  True  True  True]


In [ ]:
# float values 

Z = np.array([-1.5, -2.5, -3.5])

Z[Z < 0] = -Z[Z < 0]
print(Z)

[1.5 2.5 3.5]


In [ ]:
#78.  Distance from one point to several lines 
P0 = np.array([
    [0, 0],
    [1 ,1],
    [2, 0],
 ], dtype=float)

P1 = np.array([
     [4, 0],
     [1 ,5],
     [5, 3],
], dtype=float)

p = np.array([2, 2], dtype=float)

line_vectors = P1 - P0
point_vectors = p - P0

cross_products = (
     line_vectors[:, 0] * point_vectors[:, 1] - line_vectors[:, 1] * point_vectors[:, 0]

)
distances = np.abs(cross_products) / np.linalg.norm(line_vectors, axis=1)
print("Distances from point to lines:", distances)



Distances from point to lines: [2.         1.         1.41421356]


In [ ]:
# 79. Distance from several points to several lines 
P0 = np.array([
    [0, 0],
    [1, 1]
], dtype=float)

P1 = np.array([
    [4, 0],
    [1, 5]
], dtype=float)

P = np.array([
    [2, 2],
    [3, 1],
    [0, 4]
], dtype=float)

line_vectors = P1 - P0

point_vectors = P[None, :, :] - P0[:, None, :]

cross_products = (
    line_vectors[:, None, 0] * point_vectors[:, :, 1]
    - line_vectors[:, None, 1] * point_vectors[:, :, 0]
)

distances = np.abs(cross_products) / np.linalg.norm(
    line_vectors,
    axis=1
)[:, None]

print(distances)

[[2. 1. 4.]
 [1. 2. 1.]]


In [ ]:
# 80 Extract a centered subarray and pad where necessary 
def extract_subarray(array, centre, shape, fill=0):
    result = np.full(shape, fill, dtype=array.dtype)

    centre_row, centre_column = centre
    result_rows, result_columns = shape

    start_row = centre_row - result_rows // 2
    start_column = centre_column - result_columns // 2

    end_row = start_row + result_rows
    end_column = start_column + result_columns

    source_start_row = max(start_row, 0)
    source_start_column = max(start_column, 0)

    source_end_row = min(end_row, array.shape[0])
    source_end_column = min(end_column, array.shape[1])

    destination_start_row = source_start_row - start_row
    destination_start_column = source_start_column - start_column

    destination_end_row = (
        destination_start_row
        + source_end_row
        - source_start_row
    )

    destination_end_column = (
        destination_start_column
        + source_end_column
        - source_start_column
    )

    result[
        destination_start_row:destination_end_row,
        destination_start_column:destination_end_column
    ] = array[
        source_start_row:source_end_row,
        source_start_column:source_end_column
    ]

    return result


Z = np.arange(25).reshape(5, 5)

result = extract_subarray(
    Z,
    centre=(0, 0),
    shape=(3, 3),
    fill=-1
)

print(result)

[[-1 -1 -1]
 [-1  0  1]
 [-1  5  6]]


In [ ]:
# 81. Generate overlapping groups of 4
Z = np.arange(1, 15)

R = np.lib.stride_tricks.sliding_window_view(
    Z,
    window_shape=4
)

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [ ]:
# 82. Compute matrix rank
Z = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [1, 1, 1]
])

rank = np.linalg.matrix_rank(Z)

print("Matrix rank:", rank)

Matrix rank: 2


In [ ]:
# 83. Find the most frequent value 
Z = np.array([1, 2, 2, 3, 3, 3, 4, 4])

most_frequent = np.bincount(Z).argmax()

print("Most frequent value:", most_frequent)

Most frequent value: 3


In [ ]:
# 84 Extract all 3 * 3 blocks
Z = np.random.randint(0, 10, size=(10, 10))

blocks = np.lib.stride_tricks.sliding_window_view(
    Z,
    window_shape=(3, 3)
)

print("Blocks shape:", blocks.shape)
print(blocks)

Blocks shape: (8, 8, 3, 3)
[[[[3 3 2]
   [3 0 5]
   [0 8 7]]

  [[3 2 1]
   [0 5 8]
   [8 7 0]]

  [[2 1 1]
   [5 8 3]
   [7 0 6]]

  [[1 1 9]
   [8 3 2]
   [0 6 2]]

  [[1 9 4]
   [3 2 1]
   [6 2 0]]

  [[9 4 1]
   [2 1 8]
   [2 0 2]]

  [[4 1 3]
   [1 8 4]
   [0 2 8]]

  [[1 3 3]
   [8 4 3]
   [2 8 1]]]


 [[[3 0 5]
   [0 8 7]
   [7 4 8]]

  [[0 5 8]
   [8 7 0]
   [4 8 6]]

  [[5 8 3]
   [7 0 6]
   [8 6 1]]

  [[8 3 2]
   [0 6 2]
   [6 1 9]]

  [[3 2 1]
   [6 2 0]
   [1 9 7]]

  [[2 1 8]
   [2 0 2]
   [9 7 2]]

  [[1 8 4]
   [0 2 8]
   [7 2 9]]

  [[8 4 3]
   [2 8 1]
   [2 9 6]]]


 [[[0 8 7]
   [7 4 8]
   [7 4 5]]

  [[8 7 0]
   [4 8 6]
   [4 5 6]]

  [[7 0 6]
   [8 6 1]
   [5 6 6]]

  [[0 6 2]
   [6 1 9]
   [6 6 3]]

  [[6 2 0]
   [1 9 7]
   [6 3 8]]

  [[2 0 2]
   [9 7 2]
   [3 8 4]]

  [[0 2 8]
   [7 2 9]
   [8 4 6]]

  [[2 8 1]
   [2 9 6]
   [4 6 6]]]


 [[[7 4 8]
   [7 4 5]
   [6 0 5]]

  [[4 8 6]
   [4 5 6]
   [0 5 5]]

  [[8 6 1]
   [5 6 6]
   [5 5 3]]

  [[6 1 9]
   [6 6 3]


In [ ]:
# 85. Create a symettric 2D array 
class SymmetricArray(np.ndarray):

    def __new__(cls, values):
        array = np.asarray(values)

        if array.ndim != 2 or array.shape[0] != array.shape[1]:
            raise ValueError("The array must be square.")

        symmetric = np.triu(array)
        symmetric = symmetric + symmetric.T - np.diag(
            np.diag(symmetric)
        )

        return symmetric.view(cls)

    def __setitem__(self, index, value):
        row, column = index

        np.ndarray.__setitem__(self, (row, column), value)
        np.ndarray.__setitem__(self, (column, row), value)


Z = SymmetricArray([
    [1, 2, 3],
    [0, 4, 5],
    [0, 0, 6]
])

print(Z)

Z[0, 2] = 20

print(Z)
print(Z[0, 2] == Z[2, 0])

[[1 2 3]
 [2 4 5]
 [3 5 6]]
[[ 1  2 20]
 [ 2  4  5]
 [20  5  6]]
True


In [2]:
# 87 . Calculate 4 * 4block sums 
import numpy as np
Z = np.arange(256).reshape(16, 16)

block_sums = Z.reshape(
    4, 4,
    4, 4
).sum(axis=(1, 3))

print(block_sums)

[[ 408  472  536  600]
 [1432 1496 1560 1624]
 [2456 2520 2584 2648]
 [3480 3544 3608 3672]]


In [3]:
# 89. Get the largest values 
Z = np.array([4, 8, 1, 10, 3, 7, 15, 6])
n = 3

largest = np.partition(Z, -n)[-n:]
largest = np.sort(largest)[::-1]

print(largest)

[15 10  8]


In [4]:
#90. Build a caretesian product
def cartesian_product(*arrays):
    grids = np.meshgrid(*arrays, indexing="ij")

    product = np.stack(
        grids,
        axis=-1
    ).reshape(-1, len(arrays))

    return product


A = np.array([1, 2])
B = np.array([10, 20, 30])
C = np.array([100, 200])

result = cartesian_product(A, B, C)

print(result)

[[  1  10 100]
 [  1  10 200]
 [  1  20 100]
 [  1  20 200]
 [  1  30 100]
 [  1  30 200]
 [  2  10 100]
 [  2  10 200]
 [  2  20 100]
 [  2  20 200]
 [  2  30 100]
 [  2  30 200]]


In [5]:
# 91. Convert a regular array into a records array
Z = np.array([
    [1, 2.5, 10],
    [2, 3.5, 20],
    [3, 4.5, 30]
])

record_array = np.core.records.fromarrays(
    Z.T,
    names="id,value,quantity",
    formats="i4,f4,i4"
)

print(record_array)
print(record_array.id)
print(record_array.value)


[(1, 2.5, 10) (2, 3.5, 20) (3, 4.5, 30)]
[1 2 3]
[2.5 3.5 4.5]


C:\Users\Nicole Kasiva\AppData\Local\Temp\ipykernel_20792\1277002167.py:8: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  record_array = np.core.records.fromarrays(


In [6]:
# 93. Find the rows from A containing Elements from B
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [2, 1, 8],
    [7, 8, 9],
    [5, 4, 0],
    [1, 7, 3],
    [6, 2, 4],
    [9, 8, 7]
])

B = np.array([
    [1, 2],
    [8, 9]
])

matches = (
    A[:, None, :, None]
    == B[None, :, None, :]
).any(axis=2).all(axis=2)

for row_number, values in enumerate(B):
    print(f"Rows containing {values}:")
    print(A[matches[:, row_number]])

Rows containing [1 2]:
[[1 2 3]
 [2 1 8]]
Rows containing [8 9]:
[[7 8 9]
 [9 8 7]]


In [7]:
# 94 Find rows with unequal values 
Z = np.array([
    [1, 1, 1],
    [2, 2, 3],
    [4, 4, 4],
    [5, 6, 5],
    [7, 7, 8]
])

unequal_rows = Z[
    np.any(Z[:, 1:] != Z[:, :-1], axis=1)
]

print(unequal_rows)

[[2 2 3]
 [5 6 5]
 [7 7 8]]


In [8]:
# 96 Extract unique rows 
Z = np.array([
    [1, 2],
    [3, 4],
    [1, 2],
    [5, 6],
    [3, 4]
])

unique_rows = np.unique(Z, axis=0)

print(unique_rows)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
# 100 Bootsrap confidence
X = np.array([
    12, 15, 14, 10, 18,
    20, 13, 16, 17, 11
])

number_of_resamples = 10000

rng = np.random.default_rng(seed=42)

bootstrap_samples = rng.choice(
    X,
    size=(number_of_resamples, len(X)),
    replace=True
)

bootstrap_means = bootstrap_samples.mean(axis=1)

lower_limit, upper_limit = np.percentile(
    bootstrap_means,
    [2.5, 97.5]
)

print("Sample mean:", X.mean())
print("95% confidence interval:")
print(lower_limit, upper_limit)

Sample mean: 14.6
95% confidence interval:
12.8 16.5
