In [1]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
L2=['a','b','c','d']
L2

['a', 'b', 'c', 'd']

In [4]:
type(L2[0])      

str

In [5]:
L3= [True,1,3.14,"Hello"]
L3

[True, 1, 3.14, 'Hello']

In [6]:
[type(item) for item in L3]

[bool, int, float, str]

### Fixed type in python

In [7]:
import array as arr

In [8]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
A = arr.array("i", L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating Arrays from python lists

In [2]:
import numpy as np

In [11]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.array(L)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [14]:
#define data type of array
np.array([3.14,4,2,3], dtype='int32')

array([3, 4, 2, 3], dtype=int32)

In [ ]:
#two-dimensional array

np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

### 1d Array(One Dimensional)

In [19]:
a = np.array([1,2,3])
a.shape

(3,)

### 2d Array(Two Dimensional)

In [18]:
b = np.array([[1,2,3],[4,5,6]])
b.shape

(2, 3)

### 3d Array(Three Dimensional)

In [22]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c.shape


(2, 2, 2)

In [23]:
d= np.array([[[1,2],[3,4]],

             [[5,6],[7,8]]],)
d.shape

(2, 2, 2)

### Creating Arrays From Scratch

In [25]:
# create an array of zeros
np.zeros(5,dtype='int')

array([0, 0, 0, 0, 0])

In [26]:
#create an 3*5 array of ones
np.ones((3,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
#create an 3*5 array of 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [35]:
#create an array filled in with a linear sequence
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
np.random.random((3,3))

array([[0.34117528, 0.50602151, 0.87921681],
       [0.4566051 , 0.03303875, 0.49089587],
       [0.87135389, 0.33994426, 0.8629901 ]])

In [36]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1, (3,3))

array([[ 0.28268485, -0.37184417,  2.69183563],
       [-0.02757498,  1.20006593,  0.44573102],
       [-0.37995966,  0.44701406, -0.67134945]])

In [37]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10, (3,3))

array([[1, 9, 7],
       [1, 2, 4],
       [4, 3, 6]], dtype=int32)

In [38]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3, dtype=int)

array([4607182418800017408, 4607182418800017408, 4607182418800017408])

### Data manipulation in python


### NumPy Array Attributes

In [41]:
np.random.seed(42) # set the random seed to 42 for reproducibility
# create a one-dimensional array 
x1 = np.random.randint(10, size=6)
x1

# create a two-dimensional array
x2 = np.random.randint(10, size=(3, 4))
x2

# create a three-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))
x3

array([[[5, 1, 4, 0, 9],
        [5, 8, 0, 9, 2],
        [6, 3, 8, 2, 4],
        [2, 6, 4, 8, 6]],

       [[1, 3, 8, 1, 9],
        [8, 9, 4, 1, 3],
        [6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5]],

       [[5, 9, 3, 5, 1],
        [9, 1, 9, 3, 7],
        [6, 8, 7, 4, 1],
        [4, 7, 9, 8, 8]]], dtype=int32)

In [ ]:
#to view all our arrays at the same time
print(x1)
print(x2)
print(x3)

[6 3 7 4 6 9]
[[2 6 7 4]
 [3 7 7 2]
 [5 4 1 7]]
[[[5 1 4 0 9]
  [5 8 0 9 2]
  [6 3 8 2 4]
  [2 6 4 8 6]]

 [[1 3 8 1 9]
  [8 9 4 1 3]
  [6 7 2 0 3]
  [1 7 3 1 5]]

 [[5 9 3 5 1]
  [9 1 9 3 7]
  [6 8 7 4 1]
  [4 7 9 8 8]]]


In [43]:
x1

array([6, 3, 7, 4, 6, 9], dtype=int32)

In [44]:
print("x1 shape: ", x1.shape)
print("x1 ndim: ", x1.ndim)
print("x1 size: ", x1.size)
print("x1 dtype: ", x1.dtype)

x1 shape:  (6,)
x1 ndim:  1
x1 size:  6
x1 dtype:  int32


In [45]:
x3

array([[[5, 1, 4, 0, 9],
        [5, 8, 0, 9, 2],
        [6, 3, 8, 2, 4],
        [2, 6, 4, 8, 6]],

       [[1, 3, 8, 1, 9],
        [8, 9, 4, 1, 3],
        [6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5]],

       [[5, 9, 3, 5, 1],
        [9, 1, 9, 3, 7],
        [6, 8, 7, 4, 1],
        [4, 7, 9, 8, 8]]], dtype=int32)

In [46]:
print("x3 shape: ", x3.shape)
print("x3 ndim: ", x3.ndim)
print("x3 size: ", x3.size)
print("x3 dtype: ", x3.dtype)
print("x3 itemsize: ", x3.itemsize)
print("x3 nbytes: ", x3.nbytes)

x3 shape:  (3, 4, 5)
x3 ndim:  3
x3 size:  60
x3 dtype:  int32
x3 itemsize:  4
x3 nbytes:  240


In [47]:
x3

array([[[5, 1, 4, 0, 9],
        [5, 8, 0, 9, 2],
        [6, 3, 8, 2, 4],
        [2, 6, 4, 8, 6]],

       [[1, 3, 8, 1, 9],
        [8, 9, 4, 1, 3],
        [6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5]],

       [[5, 9, 3, 5, 1],
        [9, 1, 9, 3, 7],
        [6, 8, 7, 4, 1],
        [4, 7, 9, 8, 8]]], dtype=int32)

In [48]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [49]:
print("x3 dtype:", x3.dtype)

x3 dtype: int32


In [50]:
x3

array([[[5, 1, 4, 0, 9],
        [5, 8, 0, 9, 2],
        [6, 3, 8, 2, 4],
        [2, 6, 4, 8, 6]],

       [[1, 3, 8, 1, 9],
        [8, 9, 4, 1, 3],
        [6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5]],

       [[5, 9, 3, 5, 1],
        [9, 1, 9, 3, 7],
        [6, 8, 7, 4, 1],
        [4, 7, 9, 8, 8]]], dtype=int32)

In [ ]:
print("itemsize: ", x3.itemsize)
print("nbytes: ", x3.nbytes)

itemsize:  4
nbytes:  240


### Array Indexing: Accessing Single Elements


In [ ]:
x1

array([6, 3, 7, 4, 6, 9], dtype=int32)

In [53]:
print(x1[3])

4


In [54]:
print(x1[-1])  # Access the last element

9


In [55]:
x2

array([[2, 6, 7, 4],
       [3, 7, 7, 2],
       [5, 4, 1, 7]], dtype=int32)

In [56]:
x2[0:2, 1:3]

array([[6, 7],
       [7, 7]], dtype=int32)

In [57]:
x2[1:, 2:]

array([[7, 2],
       [1, 7]], dtype=int32)

In [58]:
x2[1,2] = 55

In [59]:
x2

array([[ 2,  6,  7,  4],
       [ 3,  7, 55,  2],
       [ 5,  4,  1,  7]], dtype=int32)

In [60]:
x2[1,0] = 12
x2 # Check the modified value

array([[ 2,  6,  7,  4],
       [12,  7, 55,  2],
       [ 5,  4,  1,  7]], dtype=int32)

### Array Slicing: Accessing Subarrays

In [61]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
# first five elements
x[:5]  # Access elements from index 0 to 4

array([0, 1, 2, 3, 4])

In [63]:
x[5:]  

array([5, 6, 7, 8, 9])

In [64]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
x[4:7]

array([4, 5, 6])

In [66]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
x[::2] # Access every second element

array([0, 2, 4, 6, 8])

In [68]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
x[1:6:2]  # Access every second element, starting from index 1

array([1, 3, 5])

In [70]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
x[::-1]  # Reverse the array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [72]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
x[5::-1]  # Access elements from index 5 to the end in reverse order

array([5, 4, 3, 2, 1, 0])

### Multi Dimensional arrays

In [74]:
x2

array([[ 2,  6,  7,  4],
       [12,  7, 55,  2],
       [ 5,  4,  1,  7]], dtype=int32)

In [75]:
x2[0:2, 1:3]

array([[ 6,  7],
       [ 7, 55]], dtype=int32)

In [76]:
print(x2[:3, 1::2]) # Access the first two rows and first three columns

[[6 4]
 [7 2]
 [4 7]]


In [77]:
x2

array([[ 2,  6,  7,  4],
       [12,  7, 55,  2],
       [ 5,  4,  1,  7]], dtype=int32)

In [78]:
x2[:3, ::-2]  # Access all rows starting from index 1, and columns starting from index 2

array([[4, 6],
       [2, 7],
       [7, 4]], dtype=int32)

In [79]:
x2

array([[ 2,  6,  7,  4],
       [12,  7, 55,  2],
       [ 5,  4,  1,  7]], dtype=int32)

In [80]:
x2[1:, 1:3] # Access all rows starting from index 1, and columns starting from index 1 to 2 (not including 3)

array([[ 7, 55],
       [ 4,  1]], dtype=int32)

In [81]:
x2

array([[ 2,  6,  7,  4],
       [12,  7, 55,  2],
       [ 5,  4,  1,  7]], dtype=int32)

In [82]:
x2[:3, 1::2]  # Access the first three rows and every second column

array([[6, 4],
       [7, 2],
       [4, 7]], dtype=int32)

In [83]:
x2

array([[ 2,  6,  7,  4],
       [12,  7, 55,  2],
       [ 5,  4,  1,  7]], dtype=int32)

In [84]:
x2[:3, 0::3]

array([[ 2,  4],
       [12,  2],
       [ 5,  7]], dtype=int32)

In [85]:
x2

array([[ 2,  6,  7,  4],
       [12,  7, 55,  2],
       [ 5,  4,  1,  7]], dtype=int32)

In [86]:
x2[1:, 0:2]

array([[12,  7],
       [ 5,  4]], dtype=int32)

In [87]:
x2[::-1, ::-1]  # Reverse both rows and columns

array([[ 7,  1,  4,  5],
       [ 2, 55,  7, 12],
       [ 4,  7,  6,  2]], dtype=int32)

### Accessing array rows and columns

In [88]:
print(x2[:, 1]) # Access the first column of x2

[6 7 4]


In [89]:
x2

array([[ 2,  6,  7,  4],
       [12,  7, 55,  2],
       [ 5,  4,  1,  7]], dtype=int32)

In [90]:
print(x2[0, :]) # Access the first row of x2

[2 6 7 4]


In [91]:
print(x2[0])

[2 6 7 4]


In [6]:
w= np.array ([4,5,6]),([7,8,9])
np.hstack([w]) #splitting columns

array([[4, 5, 6],
       [7, 8, 9]])

In [9]:

x = [2, 3, 4]
y = [7, 8, 9]
z = []
for i in range(len(x)):
    z.append(x[i] + y[i])
z

[9, 11, 13]

In [10]:
# Define two ample arrays 
a = np.array([10, 20, 30])
b = np.array([3, 4,5])
print(a)
print(b)

[10 20 30]
[3 4 5]


In [ ]:
#Addition
#np.add(a,b)
a+b

array([13, 24, 35])

In [ ]:
#Subtraction
#np.subtract(a,b)
a-b

array([ 7, 16, 25])

In [ ]:
#Unary negation
np.negative(a)
a-

In [13]:
#Multiply
np.multiply(a,b)
a*b


array([ 30,  80, 150])

### Aggregations in Numpy

In [3]:
r = np.arange(1, 11)
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
sum (r)

np.int64(55)

In [5]:
np.sum(r)

np.int64(55)

In [6]:
r2 = np.random.random(100)
r2

array([0.79593682, 0.57286092, 0.19441689, 0.18791244, 0.1824635 ,
       0.06475629, 0.45730282, 0.60344773, 0.22822543, 0.30368547,
       0.70920518, 0.76538245, 0.03849154, 0.88035991, 0.8971168 ,
       0.11209274, 0.05688344, 0.31968475, 0.09022075, 0.09282681,
       0.82420488, 0.68561499, 0.43824863, 0.94491923, 0.77188822,
       0.10043079, 0.76846735, 0.95667016, 0.07282624, 0.17849867,
       0.5793126 , 0.41077326, 0.07046675, 0.82620569, 0.67554911,
       0.97813754, 0.74519365, 0.78448512, 0.34547294, 0.05703935,
       0.67454563, 0.98824897, 0.64872921, 0.48743264, 0.78713366,
       0.08226353, 0.1190809 , 0.21089883, 0.58298592, 0.24427464,
       0.8237504 , 0.42018855, 0.45074907, 0.60769245, 0.75816198,
       0.22802941, 0.73247479, 0.19886288, 0.03270214, 0.72099538,
       0.68662436, 0.39375475, 0.08740513, 0.60218479, 0.96126408,
       0.83575723, 0.6530063 , 0.83285488, 0.86524921, 0.17373503,
       0.82413434, 0.60822541, 0.76798462, 0.51311113, 0.36643

In [7]:
sum(r2)

np.float64(51.586528347423474)

In [8]:
np.sum(r2)

np.float64(51.586528347423474)

In [9]:
%timeit sum(r2)

60.4 μs ± 16.4 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
%timeit np.sum(r2)

The slowest run took 4.98 times longer than the fastest. This could mean that an intermediate result is being cached.
48.5 μs ± 27.1 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [11]:
b_array = np.random.random(100000)

In [12]:
%timeit np.sum(b_array)

The slowest run took 5.97 times longer than the fastest. This could mean that an intermediate result is being cached.
672 μs ± 497 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [13]:
%timeit sum(b_array)

30.5 ms ± 9.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [14]:
%timeit np.sum(b_array)

530 μs ± 168 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [17]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
m.sum()

np.int64(45)

In [19]:
m.sum(axis=1)

array([ 6, 15, 24])

### Broadcasting in Numpy

In [20]:
# Adding a scalar value to an array
a = np.array ([1, 2, 3])
b = 5
a + b

array([6, 7, 8])

In [23]:
# Add 1D array to a 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
b = np.array ([10, 20, 30])
print(b.shape)
print (a + b)

(2, 3)
(3,)
[[11 22 33]
 [14 25 36]]


In [29]:
a = np.arange (3).reshape (3, 1)
b = np.arange (3)
print(a.shape)
print(b.shape)
print('--------------')
print (a)
print(b)
print('--------------')
print(a+b)

(3, 1)
(3,)
--------------
[[0]
 [1]
 [2]]
[0 1 2]
--------------
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [30]:
# arrays that are not compatible
M =  np.ones((3, 2), dtype=int)
a= np.arange(3)
a + M

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [3]:
x = np.ones((3, 2), dtype=int)
y = np.arange(2,2)
x+y

ValueError: operands could not be broadcast together with shapes (3,2) (0,) 

### Boolean Masking

In [2]:
import numpy as np

In [3]:
arr = np.array([10, 20 ,30, 40, 50])

#Create the mask 
mask = arr > 25

#using the mask
result = arr[mask]
print(arr)
print(mask)

[10 20 30 40 50]
[False False  True  True  True]


In [4]:
app = np.arange(1,11)
mask = arr > 5

print(app)
print(mask)


[ 1  2  3  4  5  6  7  8  9 10]
[ True  True  True  True  True]


### Comparison Operators as unfuncs

In [5]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [ ]:
x > 3

array([False, False, False,  True,  True])

In [7]:
x == 3

array([False, False,  True, False, False])

In [8]:
x

array([1, 2, 3, 4, 5])

In [9]:
2 * x

array([ 2,  4,  6,  8, 10])

In [10]:
x ** 2

array([ 1,  4,  9, 16, 25])

In [11]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

### Counting Entries 

In [14]:
np.random.seed(42)
x = np.random.randint(1, 13, size = 12).reshape(3,4)
x

array([[ 7,  4, 11,  8],
       [ 5,  7, 10,  3],
       [ 7, 11, 11,  8]], dtype=int32)

In [ ]:
x = np.random.randint(1, 13, size = 12).reshape(3,4)
x

array([[ 9,  2, 10,  1],
       [ 6,  3,  9, 11],
       [ 3,  4,  1,  9]], dtype=int32)

In [15]:
# how many values are less than 6
np.count_nonzero(x < 6)

np.int64(3)

In [16]:
# sum of elements less than 7 
np.sum(x < 7)

np.int64(3)

In [17]:
x

array([[ 7,  4, 11,  8],
       [ 5,  7, 10,  3],
       [ 7, 11, 11,  8]], dtype=int32)

In [ ]:
np.sum(x < 6, axis=1)# axis 1 is used to check the rows 

array([1, 2, 0])

In [ ]:
np.sum(x < 6, axis=0) #axis 0 is used to check for the columns

array([1, 1, 0, 1])

### Using np.any

In [20]:
x

array([[ 7,  4, 11,  8],
       [ 5,  7, 10,  3],
       [ 7, 11, 11,  8]], dtype=int32)

In [ ]:
np.any (x > 8) # checks whether there values greater than 8

np.True_

### Using np.all

In [ ]:
np.all(x > 8) # checks if all the values are greater than 8 

np.False_

In [ ]:
y = np.array ([10, 15, 20, 25, 30])
y

array([10, 15, 20, 25, 30])

In [24]:
y > 15

array([False, False,  True,  True,  True])

In [25]:
y < 30 

array([ True,  True,  True,  True, False])

In [ ]:
(y > 15) & (y < 30) #combining the two conditions 

array([False, False,  True,  True, False])

In [27]:
# to give us the values in integers and boolean
mask = (y > 15) & (y < 30)
result = y[mask]
print(mask)
print (result)

[False False  True  True False]
[20 25]


In [28]:
y

array([10, 15, 20, 25, 30])

In [ ]:
y[~(y > 20 )] #values not greater than 20

array([10, 15, 20])

### Fancy Indexing

#### Indexing with a list of indices

In [30]:
f = np.random.randint(1, 50, size=(5, ))
f

array([36, 40, 24,  3, 22], dtype=int32)

In [32]:
#without facncy indexing
f[0:3]

array([36, 40, 24], dtype=int32)

In [31]:
#using fancy indexing
f[[0, 1, 2]]

array([36, 40, 24], dtype=int32)

### Fancy Indexing with 2D array

In [34]:
f2 = np.arange(1, 13).reshape(3,4)
f2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
f2[[0,1,2],[0,1,2]]

array([ 1,  6, 11])

In [ ]:
#to get numbers 2,6,10 and 4,8,12
f2[:, [1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [44]:
#to get everything
f2[:, 0:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### using np.ix

In [45]:
f2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
row = np.array([0, 1, 2])
col = np.array([0, 1, 2])
f2[row,col]

#normal way

array([ 1,  6, 11])

In [49]:
#using np.ix
row = np.array([ 1, 2])
col = np.array([0, 1])
f2[np.ix_(row,col)]


array([[ 5,  6],
       [ 9, 10]])

In [50]:
arr = np.random.randint(1, 10, size =(9,))
arr

array([5, 2, 8, 6, 2, 5, 1, 6, 9], dtype=int32)

In [52]:
sorted_arr = np.sort(arr)
print(arr)
print(sorted_arr)

[5 2 8 6 2 5 1 6 9]
[1 2 2 5 5 6 6 8 9]


In [3]:
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
array_1 = np.array([[1, 2, 3], [4, 5, 6]])
array_1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
array_2 = np.array([[7, 8, 9], [10, 11, 12]])
array_2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [11]:
array_3 = np.concatenate([array_1,array_2])
array_3

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 7,  8,  9],
       [10, 11, 12]])

### Simple concatenation with pd.concat